# Generated by Django 6.0 on 2025-12-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="uploadrecord",
            table="upload_record",
        ),
    ]
