# Generated by Django 6.0 on 2025-12-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_uploadrecord_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadrecord",
            name="xml_output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadrecord",
            name="filename",
            field=models.CharField(max_length=255),
        ),
    ]
